; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define DeployDir "C:\Users\JackieLiu\Documents\build-Pastes-Qt6-CMake\pastes-deploy"
#define MyAppName "Pastes"
#define MyAppVersion "0.3"
#define MyAppPublisher "Jackie Liu"
#define MyAppURL "https://www.byteisland.com"
#define MyAppExeName "pastes.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0BF3E82A-DF86-47CB-82C4-E75052416F49}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\JackieLiu\Desktop
OutputBaseFilename=pastes-setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "{#DeployDir}\pastes.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DeployDir}\Pastes_zh_CN.qm"; DestDir: "{app}"; Flags: ignoreversion
; MinGW runtime
Source: "{#DeployDir}\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DeployDir}\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DeployDir}\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
; Qt6 runtime
Source: "{#DeployDir}\Qt6Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DeployDir}\Qt6Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DeployDir}\Qt6Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DeployDir}\Qt6Sql.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DeployDir}\Qt6Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
; Qt6 plugins
Source: "{#DeployDir}\platforms\qwindows.dll"; DestDir: "{app}\platforms"; Flags: ignoreversion
Source: "{#DeployDir}\styles\qmodernwindowsstyle.dll"; DestDir: "{app}\styles"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root:HKLM;Subkey:SOFTWARE\Microsoft\Windows\CurrentVersion\Run;ValueType: string; ValueName: Pastes;ValueData:{app}\pastes.exe;Flags: uninsdeletevalue

