#include "tests/testsupport.h"
#include "platform/macos/clipboardpolicy.h"
#include "platform/macos/clipboardmetadata.h"
#include "platform/diagnosticlog.h"

#include <QCoreApplication>
#include <QFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QTemporaryDir>
#import <AppKit/AppKit.h>

@interface PastesPromisedClipboardData : NSObject <NSPasteboardItemDataProvider>
@property NSUInteger reads;
@end

@implementation PastesPromisedClipboardData
- (void)pasteboard:(NSPasteboard *)pasteboard item:(NSPasteboardItem *)item
	provideDataForType:(NSPasteboardType)type
{
	Q_UNUSED(pasteboard);
	++_reads;
	[item setString:@"Pastes clipboard policy test" forType:type];
}
@end

namespace {

class PrivatePasteboard final
{
public:
	PrivatePasteboard(void) : board([NSPasteboard pasteboardWithUniqueName]) {}
	~PrivatePasteboard() { [board releaseGlobally]; }
	NSPasteboard *board;
};

void nativeMarkers(void)
{
	PrivatePasteboard isolated;
	NSPasteboard *board = isolated.board;
	NSArray<NSPasteboardType> *markers = @[
		@"org.nspasteboard.TransientType", @"org.nspasteboard.ConcealedType",
		@"org.nspasteboard.AutoGeneratedType", @"de.petermaurer.TransientPasteboardType",
		@"com.typeit4me.clipping", @"com.agilebits.onepassword"
	];
	for (NSPasteboardType marker in markers) {
		[board clearContents];
		PastesPromisedClipboardData *provider = [[[PastesPromisedClipboardData alloc] init] autorelease];
		NSPasteboardItem *item = [[[NSPasteboardItem alloc] init] autorelease];
		[item setData:[NSData data] forType:marker];
		[item setDataProvider:provider forTypes:@[NSPasteboardTypeString, NSPasteboardTypeFileURL]];
		require([board writeObjects:@[item]], "Could not write isolated native pasteboard");
		require(!Platform::allowsClipboardHistory(board), "Native exclusion marker was ignored");
		require(provider.reads == 0, "Filtering resolved an excluded promised payload");
	}

	/* This pre-UTI marker is declared with the legacy pasteboard API;
	 * NSPasteboardItem only accepts UTI strings. */
	[board declareTypes:@[@"Pasteboard generator type", NSPasteboardTypeString] owner:nil];
	require([board setData:[NSData data] forType:@"Pasteboard generator type"], "Could not write legacy marker");
	require([board setString:@"generated text" forType:NSPasteboardTypeString], "Could not write legacy text");
	require(!Platform::allowsClipboardHistory(board), "Legacy generator marker was ignored");

	[board clearContents];
	NSPasteboardItem *file = [[[NSPasteboardItem alloc] init] autorelease];
	[file setString:@"file:///tmp/Pastes%20test/temp/RWTemp/image.png" forType:NSPasteboardTypeFileURL];
	[file setString:@"com.tencent.xinWeChat" forType:@"org.nspasteboard.source"];
	NSPasteboardItem *transient = [[[NSPasteboardItem alloc] init] autorelease];
	[transient setString:@"automatic" forType:NSPasteboardTypeString];
	[transient setData:[NSData data] forType:@"org.nspasteboard.AutoGeneratedType"];
	[file setData:[NSData data] forType:@"com.apple.is-remote-clipboard"];
	require([board writeObjects:@[file, transient]], "Could not write multiple pasteboard items");
	require(!Platform::allowsClipboardHistory(board), "Marker on a later pasteboard item was ignored");

	/* A new unmarked copy must not inherit the old exclusion. Source app,
	 * temporary path and Universal Clipboard are not opt-out markers. */
	[board clearContents];
	NSPasteboardItem *ordinaryFile = [[[NSPasteboardItem alloc] init] autorelease];
	[ordinaryFile setString:@"file:///tmp/Pastes%20test/temp/RWTemp/image.png" forType:NSPasteboardTypeFileURL];
	[ordinaryFile setString:@"com.tencent.xinWeChat" forType:@"org.nspasteboard.source"];
	[ordinaryFile setData:[NSData data] forType:@"com.apple.is-remote-clipboard"];
	require([board writeObjects:@[ordinaryFile]], "Could not write normal file copy");
	require(Platform::allowsClipboardHistory(board), "Normal temporary file copy was excluded");
	[board clearContents];
	require([board setString:@"ordinary text" forType:NSPasteboardTypeString], "Could not write text");
	require(Platform::allowsClipboardHistory(board), "Normal text after exclusion was lost");
}

void nativeImageDeclarations(void)
{
	PrivatePasteboard isolated;
	NSPasteboard *board = isolated.board;
	PastesPromisedClipboardData *provider = [[[PastesPromisedClipboardData alloc] init] autorelease];
	NSPasteboardItem *file = [[[NSPasteboardItem alloc] init] autorelease];
	[file setString:@"file:///tmp/file.png" forType:NSPasteboardTypeFileURL];
	[file setDataProvider:provider forTypes:@[@"com.apple.icns"]];
	[board clearContents];
	require([board writeObjects:@[file]], "Could not write native file-icon fixture");
	require(!Platform::hasClipboardImageContent(board), "File-icon image conversions became content");
	require(provider.reads == 0, "Image policy resolved a promised icon");
	NSPasteboardItem *image = [[[NSPasteboardItem alloc] init] autorelease];
	[image setString:@"file:///tmp/temporary.png" forType:NSPasteboardTypeFileURL];
	[image setDataProvider:provider forTypes:@[NSPasteboardTypeTIFF]];
	[board clearContents];
	require([board writeObjects:@[image]], "Could not write declared bitmap fixture");
	require(Platform::hasClipboardImageContent(board), "A declared bitmap with a file URL was lost");
	require(provider.reads == 0, "Image policy resolved a promised bitmap");
}

void localDiagnostics(void)
{
	PrivatePasteboard isolated;
	NSPasteboard *board = isolated.board;
	QTemporaryDir directory;
	require(directory.isValid(), "Could not create isolated diagnostic directory");
	const QString path = directory.path()+"/logs/clipboard.jsonl";
	Platform::DiagnosticLog diagnostics(path);
	auto observe = [&](bool allowed, const QString &foreground) {
		diagnostics.append(Platform::clipboardMetadata(board, allowed, foreground));
	};
	auto readLog = [&] {
		QFile file(path);
		require(file.open(QIODevice::ReadOnly), "Clipboard diagnostic log was not created");
		return file.readAll();
	};
	PastesPromisedClipboardData *provider = [[[PastesPromisedClipboardData alloc] init] autorelease];
	NSPasteboardItem *item = [[[NSPasteboardItem alloc] init] autorelease];
	[item setData:[NSData data] forType:@"org.nspasteboard.AutoGeneratedType"];
	[item setDataProvider:provider forTypes:@[NSPasteboardTypeString, NSPasteboardTypeFileURL]];
	[board clearContents];
	require([board writeObjects:@[item]], "Could not write promised diagnostic fixture");
	observe(Platform::allowsClipboardHistory(board), "com.tencent.xinWeChat");
	require(provider.reads == 0, "Diagnostics resolved a promised clipboard payload");
	const QByteArray first = readLog();
	const QJsonObject record = QJsonDocument::fromJson(first).object();
	require(!record.value("captureAllowed").toBool() &&
		record.value("foregroundApp").toString() == "com.tencent.xinWeChat" &&
		record.value("changeCount").toInteger() == board.changeCount &&
		!record.value("time").toString().isEmpty() &&
		first.contains("org.nspasteboard.AutoGeneratedType"),
		"Diagnostics lost native types, policy, application or timing metadata");
	observe(false, "com.tencent.xinWeChat");
	require(readLog() == first, "Repeated policy checks duplicated the same snapshot");

	/* The same counter may gain a marker while promised content is read. */
	observe(true, "com.tencent.xinWeChat");
	require(readLog().count('\n') == 2, "A policy change at the same native counter was lost");
	[board clearContents];
	NSPasteboardItem *ordinary = [[[NSPasteboardItem alloc] init] autorelease];
	[ordinary setString:@"PRIVATE clipboard text" forType:NSPasteboardTypeString];
	[ordinary setString:@"file:///tmp/private-file-path.png" forType:NSPasteboardTypeFileURL];
	[ordinary setData:[@"PRIVATE image payload" dataUsingEncoding:NSUTF8StringEncoding] forType:NSPasteboardTypePNG];
	require([board writeObjects:@[ordinary]], "Could not write ordinary diagnostic fixture");
	observe(Platform::allowsClipboardHistory(board), "com.example.normal");
	const QByteArray ordinaryLog = readLog();
	require(ordinaryLog.count('\n') == 3 && !ordinaryLog.contains("PRIVATE") &&
		!ordinaryLog.contains("private-file-path"), "Diagnostics logged clipboard content");
}

}

int main(int argc, char **argv)
{
	QCoreApplication app(argc, argv);
	@autoreleasepool {
		return runTest("macOS native clipboard markers without payload reads", nativeMarkers) |
			runTest("native bitmap declarations exclude synthesized file icons", nativeImageDeclarations) |
			runTest("bounded private clipboard metadata diagnostics", localDiagnostics);
	}
}
