#include "tests/testsupport.h"
#include "platform/macos/clipboardpolicy.h"

#include <QCoreApplication>
#import <AppKit/AppKit.h>

@interface PastesPromisedClipboardData : NSObject <NSPasteboardItemDataProvider>
@property NSUInteger reads;
@end

@implementation PastesPromisedClipboardData
- (void)pasteboard:(NSPasteboard *)pasteboard item:(NSPasteboardItem *)item
	provideDataForType:(NSPasteboardType)type
{
	Q_UNUSED(pasteboard);
	++_reads;
	[item setString:@"Pastes clipboard policy test" forType:type];
}
@end

namespace {

class PrivatePasteboard final
{
public:
	PrivatePasteboard(void) : board([NSPasteboard pasteboardWithUniqueName]) {}
	~PrivatePasteboard() { [board releaseGlobally]; }
	NSPasteboard *board;
};

void nativeMarkers(void)
{
	PrivatePasteboard isolated;
	NSPasteboard *board = isolated.board;
	NSArray<NSPasteboardType> *markers = @[
		@"org.nspasteboard.TransientType", @"org.nspasteboard.ConcealedType",
		@"org.nspasteboard.AutoGeneratedType", @"de.petermaurer.TransientPasteboardType",
		@"com.typeit4me.clipping", @"com.agilebits.onepassword"
	];
	for (NSPasteboardType marker in markers) {
		[board clearContents];
		PastesPromisedClipboardData *provider = [[[PastesPromisedClipboardData alloc] init] autorelease];
		NSPasteboardItem *item = [[[NSPasteboardItem alloc] init] autorelease];
		[item setData:[NSData data] forType:marker];
		[item setDataProvider:provider forTypes:@[NSPasteboardTypeString, NSPasteboardTypeFileURL]];
		require([board writeObjects:@[item]], "Could not write isolated native pasteboard");
		require(!Platform::allowsClipboardHistory(board), "Native exclusion marker was ignored");
		require(provider.reads == 0, "Filtering resolved an excluded promised payload");
	}

	/* This pre-UTI marker is declared with the legacy pasteboard API;
	 * NSPasteboardItem only accepts UTI strings. */
	[board declareTypes:@[@"Pasteboard generator type", NSPasteboardTypeString] owner:nil];
	require([board setData:[NSData data] forType:@"Pasteboard generator type"], "Could not write legacy marker");
	require([board setString:@"generated text" forType:NSPasteboardTypeString], "Could not write legacy text");
	require(!Platform::allowsClipboardHistory(board), "Legacy generator marker was ignored");

	[board clearContents];
	NSPasteboardItem *file = [[[NSPasteboardItem alloc] init] autorelease];
	[file setString:@"file:///tmp/Pastes%20test/temp/RWTemp/image.png" forType:NSPasteboardTypeFileURL];
	[file setString:@"com.tencent.xinWeChat" forType:@"org.nspasteboard.source"];
	NSPasteboardItem *transient = [[[NSPasteboardItem alloc] init] autorelease];
	[transient setString:@"automatic" forType:NSPasteboardTypeString];
	[transient setData:[NSData data] forType:@"org.nspasteboard.AutoGeneratedType"];
	[file setData:[NSData data] forType:@"com.apple.is-remote-clipboard"];
	require([board writeObjects:@[file, transient]], "Could not write multiple pasteboard items");
	require(!Platform::allowsClipboardHistory(board), "Marker on a later pasteboard item was ignored");

	/* A new unmarked copy must not inherit the old exclusion. Source app,
	 * temporary path and Universal Clipboard are not opt-out markers. */
	[board clearContents];
	NSPasteboardItem *ordinaryFile = [[[NSPasteboardItem alloc] init] autorelease];
	[ordinaryFile setString:@"file:///tmp/Pastes%20test/temp/RWTemp/image.png" forType:NSPasteboardTypeFileURL];
	[ordinaryFile setString:@"com.tencent.xinWeChat" forType:@"org.nspasteboard.source"];
	[ordinaryFile setData:[NSData data] forType:@"com.apple.is-remote-clipboard"];
	require([board writeObjects:@[ordinaryFile]], "Could not write normal file copy");
	require(Platform::allowsClipboardHistory(board), "Normal temporary file copy was excluded");
	[board clearContents];
	require([board setString:@"ordinary text" forType:NSPasteboardTypeString], "Could not write text");
	require(Platform::allowsClipboardHistory(board), "Normal text after exclusion was lost");
}

}

int main(int argc, char **argv)
{
	QCoreApplication app(argc, argv);
	@autoreleasepool {
		return runTest("macOS native clipboard markers without payload reads", nativeMarkers);
	}
}
