# Inspect distribution metadata and native package databases, not installed
# build tools: dpkg and rpm can both be present on the same system.
function(pastes_select_linux_generator root_dir output)
    set(generator "TGZ")
    if(root_dir)
        set(release_file "${root_dir}/etc/os-release")
        if(NOT EXISTS "${release_file}")
            set(release_file "${root_dir}/usr/lib/os-release")
        endif()
        set(distributions "")
        if(EXISTS "${release_file}")
            file(STRINGS "${release_file}" release_lines REGEX "^(ID|ID_LIKE)=")
            foreach(line IN LISTS release_lines)
                string(REGEX REPLACE "^[^=]+=" "" value "${line}")
                string(REGEX REPLACE "^[\"']|[\"']$" "" value "${value}")
                string(TOLOWER "${value}" value)
                string(APPEND distributions " ${value}")
            endforeach()
        endif()
        if(distributions MATCHES "(^| )(debian|ubuntu)( |$)")
            set(generator "DEB")
        elseif(distributions MATCHES "(^| )(fedora|rhel|centos|rocky|almalinux|ol|suse|sles|opensuse(-[a-z]+)?)( |$)")
            set(generator "RPM")
        elseif(EXISTS "${root_dir}/var/lib/dpkg/status")
            set(generator "DEB")
        else()
            # Kylin's desktop and server variants can share ID=kylin while
            # using different package formats. Recognize RPM database layouts.
            foreach(database IN ITEMS var/lib/rpm usr/lib/sysimage/rpm)
                foreach(filename IN ITEMS Packages Packages.db rpmdb.sqlite)
                    if(EXISTS "${root_dir}/${database}/${filename}")
                        set(generator "RPM")
                    endif()
                endforeach()
            endforeach()
        endif()
    endif()
    set(${output} "${generator}" PARENT_SCOPE)
endfunction()
