#include "platform/macos/clipboardpolicy.h"

#import <AppKit/AppKit.h>

namespace {

bool hasExcludedType(NSArray<NSPasteboardType> *types)
{
	/* Shared and legacy opt-out markers documented at https://nspasteboard.org/.
	 * Their presence is sufficient; their payload may be empty or promised. */
	static NSSet<NSPasteboardType> *const excluded = [[NSSet alloc] initWithArray:@[
		@"org.nspasteboard.TransientType",
		@"org.nspasteboard.AutoGeneratedType",
		@"org.nspasteboard.ConcealedType",
		@"de.petermaurer.TransientPasteboardType",
		@"com.typeit4me.clipping",
		@"Pasteboard generator type",
		@"com.agilebits.onepassword"
	]];
	for (NSPasteboardType type in types) {
		if ([excluded containsObject:type]) return true;
	}
	return false;
}

}

bool Platform::allowsClipboardHistory(NSPasteboard *pasteboard)
{
	if (!pasteboard || hasExcludedType(pasteboard.types)) return false;
	/* A multi-item pasteboard may carry the marker on a later item. */
	for (NSPasteboardItem *item in pasteboard.pasteboardItems) {
		if (hasExcludedType(item.types)) return false;
	}
	return true;
}
