name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout pastes source code
        uses: actions/checkout@v4
      - name: Update apt repository
        run: sudo apt-get update -y
      - name: Install build dependencies
        run: sudo apt-get install -y build-essential cmake qt6-base-dev qt6-tools-dev qt6-tools-dev-tools libglib2.0-dev libxtst-dev libx11-dev pkg-config
      - name: CMake configure & build
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release;
          cmake --build build -j$(nproc);
