# windows.yml
name: Windows
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: ['6.8.*']
        qt_target: [desktop]
        qt_arch: [win64_msvc2022_64]
        include:
          - qt_arch: win64_msvc2022_64
            msvc_arch: x64
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: build-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
